### ISSUE TITLE
Create output files on first run

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#144]
When running the transformation for the first time, we get errors if the output folders don't exist:

```
java.io.FileNotFoundException: app/resources/output/DE/DE-1a.xml (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:206)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:95)
	at org.culturegraph.mf.stream.sink.XmlFilenameWriter.literal(XmlFilenameWriter.java:104)
	at org.culturegraph.mf.stream.pipe.XmlElementSplitter.endElement(XmlElementSplitter.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.culturegraph.mf.stream.converter.xml.XmlDecoder.process(XmlDecoder.java:63)
	at org.culturegraph.mf.stream.converter.xml.XmlDecoder.process(XmlDecoder.java:41)
	at org.culturegraph.mf.stream.source.FileOpener.process(FileOpener.java:88)
	at org.culturegraph.mf.stream.source.FileOpener.process(FileOpener.java:40)
	at transformation.Sigel.processSigelSplitting(Sigel.java:58)
	at transformation.Enrich.process(Enrich.java:90)
	at controllers.Transformation.transformFullSet(Transformation.java:52)
	at Global.onStart(Global.java:23)
	at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:22)
	at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at play.core.server.NettyServer.main(NettyServer.scala)
org.culturegraph.mf.exceptions.MetafactureException: java.io.FileNotFoundException: app/resources/output/DE/DE-1a.xml (No such file or directory)
	at org.culturegraph.mf.stream.sink.XmlFilenameWriter.literal(XmlFilenameWriter.java:121)
	at org.culturegraph.mf.stream.pipe.XmlElementSplitter.endElement(XmlElementSplitter.java:148)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.culturegraph.mf.stream.converter.xml.XmlDecoder.process(XmlDecoder.java:63)
	at org.culturegraph.mf.stream.converter.xml.XmlDecoder.process(XmlDecoder.java:41)
	at org.culturegraph.mf.stream.source.FileOpener.process(FileOpener.java:88)
	at org.culturegraph.mf.stream.source.FileOpener.process(FileOpener.java:40)
	at transformation.Sigel.processSigelSplitting(Sigel.java:58)
	at transformation.Enrich.process(Enrich.java:90)
	at controllers.Transformation.transformFullSet(Transformation.java:52)
	at Global.onStart(Global.java:23)
	at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:22)
	at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.io.FileNotFoundException: app/resources/output/DE/DE-1a.xml (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:206)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:95)
	at org.culturegraph.mf.stream.sink.XmlFilenameWriter.literal(XmlFilenameWriter.java:104)

```

**Comment by fsteeg** [comment]
Resolved with ca953625e21ae4680240d2a5908c06c57f66381b
